//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Ordens = new HashSet<Orden>();
        }
    
        public int ID { get; set; }

		[Required(ErrorMessage ="El Nombre es obligatorio")]
        public string Nombre { get; set; }

		[Required(ErrorMessage = "El Apellido es obligatorio")]
		public string Apellido { get; set; }

		[Required(ErrorMessage = "La Cedula es obligatorio")]
		public string Cedula { get; set; }

		[Required(ErrorMessage = "La Fecha es obligatorio")]
		public System.DateTime FechaRegistro { get; set; }

		[Required(ErrorMessage = "La Dirección es obligatorio")]
		public string Direccion { get; set; }

		[Required(ErrorMessage = "El Correo es obligatorio")]
		public string Correo { get; set; }

		[Required(ErrorMessage = "El Genero es obligatorio")]
		public string Genero { get; set; }

		[Required(ErrorMessage = "El Teléfono es obligatorio")]
		public string Telefono { get; set; }

		[Required(ErrorMessage = "El Usuario es obligatorio")]
		public int Id_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Ordens { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
