//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class DetalleOrden
    {
        public int ID { get; set; }

		[Required(ErrorMessage = "El Cantidad es Requerido")]
		public int Cantidad { get; set; }

		[Required(ErrorMessage = "El Total Detalle es Requerido")]
		public decimal TotalDetalle { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Orden { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Vehiculo { get; set; }
    
        public virtual Orden Orden { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
