
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VentaVehiculoModelDB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empleado()
    {

        this.FacturasOrdenes = new HashSet<FacturasOrdene>();

        this.Empleados1 = new HashSet<Empleado>();

    }


    public int ID { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Cedula { get; set; }

    public System.DateTime FechaRegistro { get; set; }

    public string Direccion { get; set; }

    public string Correo { get; set; }

    public string Genero { get; set; }

    public string Telefono { get; set; }

    public int Jefe { get; set; }

    public int Id_Usuario { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FacturasOrdene> FacturasOrdenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empleado> Empleados1 { get; set; }

    public virtual Empleado Empleado1 { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
