//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.FacturasOrdenes = new HashSet<FacturasOrdene>();
            this.Empleados1 = new HashSet<Empleado>();
        }
    
        public int ID { get; set; }

		[Required(ErrorMessage ="El Nombre es Requerido")]
        public string Nombre { get; set; }

		[Required(ErrorMessage = "El Apellido es Requerido")]
		public string Apellido { get; set; }

		[Required(ErrorMessage = "El Cedula es Requerido")]
		public string Cedula { get; set; }

		[Required(ErrorMessage = "El Fecha es Requerido")]
		public System.DateTime FechaRegistro { get; set; }

		[Required(ErrorMessage = "La Dirección es Requerido")]
		public string Direccion { get; set; }

		[Required(ErrorMessage = "El Email es Requerido")]
		[EmailAddress(ErrorMessage = "Ingrese un Email Válido")]
		public string Correo { get; set; }

		[Required(ErrorMessage = "El Genero es Requerido")]
		public string Genero { get; set; }

		[Required(ErrorMessage = "El Telefono es Requerido")]
		public string Telefono { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Jefe { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasOrdene> FacturasOrdenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleados1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
