//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class FacturasOrdene
    {
        public int ID { get; set; }

		[Required(ErrorMessage = "El Fecha es Requerido")]
		public System.DateTime Fecha { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Empleado { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Orden { get; set; }

		[Required(ErrorMessage = "El Tipo de Pago es Requerido")]
		public string TipoPago { get; set; }

		[Required(ErrorMessage = "El Cambio es Requerido")]
		public decimal Cambio { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
