//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturasOrdene
    {
        public int ID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Orden { get; set; }
        public string TipoPago { get; set; }
        public decimal Cambio { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Orden Orden { get; set; }
    }
}
