//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.DetalleOrdens = new HashSet<DetalleOrden>();
            this.FacturasOrdenes = new HashSet<FacturasOrdene>();
        }
    
        public int ID { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Cliente { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Empleado { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_TipoOrden { get; set; }

		[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_EstadoOrden { get; set; }

		[Required(ErrorMessage = "El Fecha es Requerido")]
		public System.DateTime Fecha { get; set; }

		[Required(ErrorMessage = "El SubTotal es Requerido")]
		public decimal SubTotal { get; set; }

		[Required(ErrorMessage = "El Itbs es Requerido")]
		public decimal Itbis { get; set; }

		[Required(ErrorMessage = "El Total es Requerido")]
		public decimal Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrdens { get; set; }
        public virtual EstadoOrden EstadoOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturasOrdene> FacturasOrdenes { get; set; }
    }
}
