//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Suplidore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suplidore()
        {
            this.Vehiculos = new HashSet<Vehiculo>();
        }
    
        public int ID { get; set; }

		[Required(ErrorMessage = "El Nombre es Requerido")]
		public string NombreEmpresa { get; set; }

		[Required(ErrorMessage = "La Dirección es Requerido")]
		public string Direccion { get; set; }

		[Required(ErrorMessage = "El Teléfono es Requerido")]
		public string Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculos { get; set; }
    }
}
