//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaVehiculoModelDB.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.DetalleOrdens = new HashSet<DetalleOrden>();
            this.ImagenVehiculos = new HashSet<ImagenVehiculo>();
            this.InvetarioVehiculoes = new HashSet<InvetarioVehiculo>();
        }
    
        public int ID { get; set; }

		//[Required(ErrorMessage = "El precio es Requerido")]
		public decimal Precio { get; set; }

		//[Required(ErrorMessage = "El Kilometraje es Requerido")]
		public decimal Kilometraje { get; set; }

		//[Required(ErrorMessage = "El Color es Requerido")]
		public string Color { get; set; }

		//[Required(ErrorMessage = "El Año es Requerido")]
		public string Año { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Minimo un Caracter")]
		public int Id_Combustible { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Minimo un Caracter")]
		public int Id_TipoVehiculo { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Asiento { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Estado { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Modelo { get; set; }

		//[MinLength(1, ErrorMessage = " Ingrese Mínimo un Caracter")]
		public int Id_Suplidor { get; set; }
    
        public virtual AsientosVehiculo AsientosVehiculo { get; set; }
        public virtual CombustibleVehiculo CombustibleVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrden> DetalleOrdens { get; set; }
        public virtual EstadoVehiculo EstadoVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenVehiculo> ImagenVehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvetarioVehiculo> InvetarioVehiculoes { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Suplidore Suplidore { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
