
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VentaVehiculoModelDB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vehiculo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vehiculo()
    {

        this.DetalleOrdens = new HashSet<DetalleOrden>();

        this.ImagenVehiculos = new HashSet<ImagenVehiculo>();

        this.InvetarioVehiculoes = new HashSet<InvetarioVehiculo>();

    }


    public int ID { get; set; }

    public decimal Precio { get; set; }

    public decimal Kilometraje { get; set; }

    public string Color { get; set; }

    public string Año { get; set; }

    public int Id_Combustible { get; set; }

    public int Id_TipoVehiculo { get; set; }

    public int Id_Asiento { get; set; }

    public int Id_Estado { get; set; }

    public int Id_Modelo { get; set; }

    public int Id_Suplidor { get; set; }



    public virtual AsientosVehiculo AsientosVehiculo { get; set; }

    public virtual CombustibleVehiculo CombustibleVehiculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleOrden> DetalleOrdens { get; set; }

    public virtual EstadoVehiculo EstadoVehiculo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ImagenVehiculo> ImagenVehiculos { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InvetarioVehiculo> InvetarioVehiculoes { get; set; }

    public virtual Modelo Modelo { get; set; }

    public virtual Suplidore Suplidore { get; set; }

    public virtual TipoVehiculo TipoVehiculo { get; set; }

}

}
