

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VentaVehiculoModelDB.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class VentasVehiculoDBEntities : DbContext
{
    public VentasVehiculoDBEntities()
        : base("name=VentasVehiculoDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AsientosVehiculo> AsientosVehiculos { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<CombustibleVehiculo> CombustibleVehiculos { get; set; }

    public virtual DbSet<DetalleOrden> DetalleOrdens { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<EstadoOrden> EstadoOrdens { get; set; }

    public virtual DbSet<EstadoVehiculo> EstadoVehiculos { get; set; }

    public virtual DbSet<ImagenVehiculo> ImagenVehiculos { get; set; }

    public virtual DbSet<InvetarioVehiculo> InvetarioVehiculoes { get; set; }

    public virtual DbSet<Marca> Marcas { get; set; }

    public virtual DbSet<Modelo> Modelos { get; set; }

    public virtual DbSet<Orden> Ordens { get; set; }

    public virtual DbSet<Suplidore> Suplidores { get; set; }

    public virtual DbSet<TipoVehiculo> TipoVehiculos { get; set; }

    public virtual DbSet<TraccionVehiculo> TraccionVehiculos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Vehiculo> Vehiculos { get; set; }

    public virtual DbSet<FacturasOrdene> FacturasOrdenes { get; set; }

}

}

